# docker-compose -f docker-compose.yml --env-file .env up -d --build
services:
  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - "${JUPYTER_PORT}:${JUPYTER_PORT}"
    volumes:
      - ./Torch_O:${JUPYTER_DIR}
    environment:
      JUPYTER_PORT: ${JUPYTER_PORT}
      JUPYTER_DIR: ${JUPYTER_DIR}
      JUPYTER_NOTEBOOK_PASSWORD: ${JUPYTER_PASSWORD}
      JUPYTER_APP_ALLOW_ORIGIN: ${JUPYTER_APP_ALLOW_ORIGIN}
      JUPYTER_APP_IP: ${JUPYTER_APP_IP}
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
  